"""
Components + Features for each module, inferred from v20 spec content.

Status values: 'built' | 'in_progress' | 'planned'

NOTE: I have NO knowledge of which of these are actually built in Bubble.
I'm defaulting everything to 'planned'. User will correct status after review.
"""

COMPONENTS_FEATURES = {

    # ═══ REPORTING ═══
    'reporting': {
        'components': [
            ('Report Directory',           'Main page listing all reports with filters, search, pagination, and stats banner', 'planned'),
            ('Create Report',              'Popup for drafting a new report — type, group, subject, people, details, attachments', 'planned'),
            ('Edit Report',                'Popup for editing a draft/open report (same fields as Create)', 'planned'),
            ('Report Preview',             'Floating group right-side panel showing full report details with actions sidebar', 'planned'),
            ('Report Status Pipeline',    'Status bar showing current stage in the pipeline (Draft → Submitted → Verified → Reviewed → Sent → Responded → Closed → Final)', 'planned'),
            ('Comments & Thread',          'Comment list + composer inside report preview', 'planned'),
            ('Responses',                  'Response thread from department recipient back to reporter', 'planned'),
            ('File Attachments',           'Attachment list with upload, preview, download', 'planned'),
            ('Send to Department',         'Confirmation dialog before sending report to receiving department', 'planned'),
            ('Close Report',               'Confirmation dialog with optional close note', 'planned'),
            ('Reopen Report',              'Admin-only dialog to reopen a closed report', 'planned'),
            ('Report PDF Preview',         'Rendered PDF view of the report for export / print', 'planned'),
            ('Report Filters Sidebar',     'Filter controls for status, type, group, department, date range, fiscal week', 'planned'),
            ('Report Stats Banner',        'KPI cards above the directory (total, by group, by status, financial impact)', 'planned'),
            ('Report Collections',         'Saved filter presets shareable across team', 'planned'),
            ('Revision History',           'List of edits made to a submitted report with diff viewer', 'planned'),
            ('Audit Trail View',           'ActivityLog entries scoped to this specific report', 'planned'),
            ('Roles & Permissions Sidebar','Reusable component visible on every module page (per CRS design pattern)', 'planned'),
        ],
        'features': [
            ('Create report (draft)',          'User creates a new report in Draft status', 'planned'),
            ('Edit own draft report',          'Creator can edit any field before submission', 'planned'),
            ('Delete own draft report',        'Creator can delete an unsubmitted draft', 'planned'),
            ('Submit report',                  'Draft → Submitted, triggers verification notifications', 'planned'),
            ('Verify report',                  'Verifier with permission changes Submitted → Verified', 'planned'),
            ('Review report',                  'Reviewer with permission changes Verified → Reviewed', 'planned'),
            ('Send report to department',      'Reviewed → Sent, notifies recipient department', 'planned'),
            ('Respond to report',              'Recipient department replies, Sent → Responded', 'planned'),
            ('Close report',                   'Responded → Closed by reporter/reviewer', 'planned'),
            ('Final-close report',             'Closed → Final by admin (locks record)', 'planned'),
            ('Reopen closed report',           'Admin-only, Closed → Reopened with audit event', 'planned'),
            ('Add comment on report',          'Any viewer with comment permission adds a comment', 'planned'),
            ('Reply to comment',               'Threaded replies', 'planned'),
            ('Mention user in comment',        '@mention triggers notification to mentioned user', 'planned'),
            ('Attach file to report',          'Upload PDF, image, doc, up to configured size limit', 'planned'),
            ('Download attachment',            'Download any attached file', 'planned'),
            ('Delete attachment',              'Remove an attachment (permission-gated)', 'planned'),
            ('Export report as PDF',           'Render and download report as PDF with letterhead', 'planned'),
            ('Filter reports',                 'By status, group, type, department, date, fiscal week', 'planned'),
            ('Search reports',                 'Full-text search via Typesense', 'planned'),
            ('Save filter preset',             'Save current filter combination as reusable collection', 'planned'),
            ('Share filter preset with team',  'Make a collection visible to others in the company', 'planned'),
            ('Bulk-download reports',          'Select multiple reports, download as ZIP of PDFs', 'planned'),
            ('View report KPIs',               'See aggregate stats in the stats banner', 'planned'),
            ('Track SLA breaches',             'Reports overdue against response SLA are flagged', 'planned'),
            ('View revision history',          'See who edited what when on a report', 'planned'),
            ('View audit trail',               'See all ActivityLog events scoped to this report', 'planned'),
        ],
    },

    # ═══ TASK MANAGEMENT ═══
    'task-management': {
        'components': [
            ('Task Manager',              'Main page with List / Kanban / Minimal view modes and filters', 'planned'),
            ('Create Task',               'Popup for creating a new task — title, assignee, priority, due date, tags, description', 'planned'),
            ('Edit Task',                 'Popup for editing an existing task', 'planned'),
            ('Task Detail Panel',         'Floating group right-side panel with full task details, subtasks, comments, attachments', 'planned'),
            ('Subtask List',              'Nested checklist of subtasks within a task', 'planned'),
            ('Subtask Updates',           'Activity timeline inside a subtask (status changes, comments)', 'planned'),
            ('Task Comments',             'Comment thread on task', 'planned'),
            ('Task Tags',                 'Tag picker + tag management (soft-deletable lookup)', 'planned'),
            ('Task Priority Selector',    'Priority picker (Low / Med / High / Critical)', 'planned'),
            ('Task Status Pipeline',      'Status flow: Backlog → Planned → In Progress → Review → Testing → Done (+ Blocked / Canceled)', 'planned'),
            ('Task Filters Sidebar',      'Filter controls for status, assignee, priority, tag, due date', 'planned'),
            ('Task Stats Banner',         'KPI cards (total, overdue, blocked, completed)', 'planned'),
            ('Link to Report',            'Attach a related report to a task', 'planned'),
            ('Roles & Permissions Sidebar','Reusable component on every module page', 'planned'),
        ],
        'features': [
            ('Create task',                    'Any user with task.create can create a task', 'planned'),
            ('Assign task to user',            'Assign to self or others', 'planned'),
            ('Edit task',                      'Update any field on an open task', 'planned'),
            ('Delete task',                    'Soft-delete (cancel) a task', 'planned'),
            ('Move task through pipeline',     'Change status following the defined flow', 'planned'),
            ('Block / unblock task',           'Mark task as blocked with reason', 'planned'),
            ('Add subtask',                    'Create a subtask under a parent task', 'planned'),
            ('Complete subtask',               'Check off a subtask', 'planned'),
            ('Comment on task',                'Add comment to task thread', 'planned'),
            ('Reply to task comment',          'Threaded replies', 'planned'),
            ('Attach file to task',            'Upload attachments', 'planned'),
            ('Tag task',                       'Add/remove tags', 'planned'),
            ('Set task priority',              'Change priority level', 'planned'),
            ('Set task due date',              'Schedule deadline', 'planned'),
            ('Link task to report',            'Attach a report as context', 'planned'),
            ('Filter tasks',                   'By any combination of assignee, status, priority, tag, date, linked report', 'planned'),
            ('Switch view mode',               'Toggle between List, Kanban, Minimal', 'planned'),
            ('Mark task as overdue',           'Automatic flag once past due date', 'planned'),
            ('Receive task assignment notification','Assignee notified in-app + email', 'planned'),
            ('Receive due-date reminder',      'Notification before deadline', 'planned'),
            ('View task audit trail',          'See who changed what on the task', 'planned'),
        ],
    },

    # ═══ REQUEST FOR INVESTIGATION ═══
    'request-for-investigation': {
        'components': [
            ('RFI Directory',             'Main page listing all RFIs — Received / Sent tabs + filters', 'planned'),
            ('Create RFI',                'Popup for drafting a new investigation request', 'planned'),
            ('Edit RFI',                  'Popup for editing a draft RFI', 'planned'),
            ('RFI Detail Panel',          'Floating group with full RFI, response thread, evidence, actions sidebar', 'planned'),
            ('RFI Status Pipeline',       'Status flow: Draft → Sent → Accepted / Declined → In Progress → Completed → Closed', 'planned'),
            ('Accept / Decline RFI',      'Dialog for responding department to accept or decline with reason', 'planned'),
            ('RFI Response Thread',       'Messages between requester and investigator', 'planned'),
            ('Evidence Attachments',      'Files attached as investigation evidence', 'planned'),
            ('RFI Filters Sidebar',       'Filter by status, from/to department, priority, date', 'planned'),
            ('Link to Report',            'Reference the originating report', 'planned'),
            ('Roles & Permissions Sidebar','Reusable component', 'planned'),
        ],
        'features': [
            ('Create RFI',                     'Requester drafts investigation request', 'planned'),
            ('Send RFI to department',         'Draft → Sent', 'planned'),
            ('Accept RFI',                     'Recipient accepts, Sent → Accepted', 'planned'),
            ('Decline RFI',                    'Recipient declines with reason, Sent → Declined', 'planned'),
            ('Start investigation',            'Accepted → In Progress', 'planned'),
            ('Complete investigation',         'In Progress → Completed with findings', 'planned'),
            ('Close RFI',                      'Completed → Closed by requester', 'planned'),
            ('Exchange messages on RFI',       'Threaded communication between requester and investigator', 'planned'),
            ('Attach evidence to RFI',         'Upload files as investigation artifacts', 'planned'),
            ('Link RFI to source report',      'Reference the report that triggered this RFI', 'planned'),
            ('Filter RFIs',                    'By status, department, priority, date range', 'planned'),
            ('Receive RFI assignment notification','Department lead notified when RFI received', 'planned'),
            ('Escalate RFI',                   'Flag as high-priority or escalate to admin', 'planned'),
        ],
    },

    # ═══ EMPLOYEE MANAGEMENT ═══
    'employee-management': {
        'components': [
            ('Employee Directory',          'Main page — list/grid of employees with filters, search, and org-tree view', 'planned'),
            ('Create Employee',             'Popup for creating a new employee (or triggered by Onboarding conversion)', 'planned'),
            ('Edit Employee',               'Popup for updating employee profile fields', 'planned'),
            ('Employee Detail Panel',       'Floating group showing profile, assignment, history, documents, notes, skills tabs', 'planned'),
            ('Employee Profile Tab',        'Identity, contact, employment details within detail panel', 'planned'),
            ('Assignment Tab',              'Current role, department, section, position, property + reporting line', 'planned'),
            ('Leave & Separation Tab',      'Leave history, separation date/reason, rehire eligibility', 'planned'),
            ('Documents Tab',               'Uploaded documents with expiry tracking', 'planned'),
            ('Notes Tab',                   'Private/shared notes on employee', 'planned'),
            ('Skills Tab',                  'Skill list with level ratings', 'planned'),
            ('History Timeline',            'Chronological record of all changes (role, department, documents, etc.)', 'planned'),
            ('Anonymize Employee',          'Admin-only dialog with typed confirmation for GDPR anonymization', 'planned'),
            ('Org Hierarchy View',          'Visual tree of Division → Section → Department → Position', 'planned'),
            ('Employee Filters Sidebar',    'Filter by department, status, property, role, hire date', 'planned'),
            ('Document Expiry Reminders',   'Dashboard list of documents expiring soon', 'planned'),
            ('Roles & Permissions Sidebar', 'Reusable component', 'planned'),
        ],
        'features': [
            ('Create employee record',            'HR creates a new employee', 'planned'),
            ('Edit employee profile',             'Update identity, contact, employment fields', 'planned'),
            ('Assign role / department / position','Attach employee to org hierarchy', 'planned'),
            ('Move employee (reassignment)',      'Change department/role with effective date', 'planned'),
            ('Record leave',                      'Log leave period', 'planned'),
            ('Separate employee',                 'Mark as separated with reason + date', 'planned'),
            ('Mark rehire eligible',              'Flag for rehire eligibility', 'planned'),
            ('Upload employee document',          'Attach ID, contract, medical, etc.', 'planned'),
            ('Set document expiry date',          'For documents that expire (medical, license)', 'planned'),
            ('Download employee document',        'Permission-gated', 'planned'),
            ('Add note to employee',              'Private or shared note', 'planned'),
            ('Add skill',                         'Add skill with level to employee', 'planned'),
            ('View employee history',             'See full audit timeline of changes', 'planned'),
            ('Anonymize employee (GDPR)',         'Two-step: separate, then anonymize — admin-only', 'planned'),
            ('Filter employee directory',         'By department, status, property, etc.', 'planned'),
            ('View org tree',                     'Navigate Division → Section → Department → Position', 'planned'),
            ('Receive document expiry reminder',  'Notification when document approaches expiry', 'planned'),
            ('Multi-property employee assignment','Employee can belong to multiple properties', 'planned'),
        ],
    },

    # ═══ ONBOARDING + JOB BOARD ═══
    'onboarding-job-board': {
        'components': [
            # Public-facing
            ('Public Job Board',              'Unauthenticated page listing all open positions per company', 'planned'),
            ('Job Opening Detail (Public)',   'Public page with job description, requirements, apply button', 'planned'),
            ('7-Step Application Form',       'Public multi-step application flow (guest or account-based)', 'planned'),
            ('Applicant Portal',              'Authenticated applicant dashboard — their applications, profile, drafts', 'planned'),
            ('Applicant Signup / Login',      'Public auth pages for applicants', 'planned'),
            ('Password Reset (Applicant)',    'Public password reset flow', 'planned'),
            ('Email Verification',            'Applicant verifies email after signup', 'planned'),
            ('Application Status Lookup',     'Guest flow: check status via reference code + email', 'planned'),
            ('Draft Resume Link',             'Email-link flow for resuming an unsubmitted draft', 'planned'),
            # Internal admin
            ('Hiring Directory',              'Admin page listing all job openings', 'planned'),
            ('Create Job Opening',            'Popup for creating a new opening', 'planned'),
            ('Edit Job Opening',              'Popup for editing opening details', 'planned'),
            ('Job Opening Translation Editor','Popup for managing localized versions of the opening', 'planned'),
            ('Screening Questions Editor',    'Manage per-opening screening questions', 'planned'),
            ('Applicant Directory',           'List of applicants with filters', 'planned'),
            ('Applicant Detail View',         '9-tab detail view — Profile, Files, Screening, Interview, Pipeline, Notes, History, GDPR, Conversion', 'planned'),
            ('Applicant Pipeline Board',      'Kanban-style view of applicants by stage', 'planned'),
            ('Interview Scheduler',           'Schedule and log interviews with applicant', 'planned'),
            ('Conversion Wizard',             'Convert Applicant → Employee with field mapping', 'planned'),
            ('Duplicate Applicant Detector',  'Flag potential duplicate applications', 'planned'),
            ('Onboarding Template Editor',    'Create/edit reusable onboarding checklists', 'planned'),
            ('Onboarding Checklist',          'Per-employee onboarding task list', 'planned'),
            ('GDPR Data Export (Applicant)',  'Export all data for an applicant (subject access request)', 'planned'),
            ('GDPR Erasure Request',          'Handle right-to-erasure requests', 'planned'),
            ('Retention Settings Panel',      'Configure data retention periods per category', 'planned'),
            ('Roles & Permissions Sidebar',   'Reusable component', 'planned'),
        ],
        'features': [
            # Public applicant flows
            ('Browse public job openings',            'Anyone can view open positions', 'planned'),
            ('Apply as guest',                        'Submit application without creating an account', 'planned'),
            ('Apply as registered applicant',         'Submit application using existing applicant account', 'planned'),
            ('Create applicant account',              'Signup with email + password', 'planned'),
            ('Log in to applicant portal',            'Authenticate via session token', 'planned'),
            ('Reset applicant password',              'Request + confirm password reset', 'planned'),
            ('Verify applicant email',                'Confirm email via verification link', 'planned'),
            ('Save application draft',                'Persist in-progress application for later', 'planned'),
            ('Request draft resume link',             'Email link to resume unsubmitted draft', 'planned'),
            ('Lookup application status (guest)',     'Guest can check status via reference code + email', 'planned'),
            ('View own applications (applicant)',     'Logged-in applicant sees their submissions', 'planned'),
            ('Withdraw application',                  'Applicant cancels their own application', 'planned'),
            # Internal hiring flows
            ('Create job opening',                    'Recruiter/admin creates opening', 'planned'),
            ('Publish / unpublish job opening',       'Toggle public visibility', 'planned'),
            ('Edit job opening',                      'Update details', 'planned'),
            ('Close job opening',                     'Mark as filled or cancelled', 'planned'),
            ('Add opening translation',               'Add localized version of opening', 'planned'),
            ('Configure screening questions',         'Per-opening questions', 'planned'),
            ('Review applicant profile',              'Open applicant detail view', 'planned'),
            ('Move applicant through pipeline',       'Change pipeline stage', 'planned'),
            ('Reject applicant',                      'Mark as rejected with reason', 'planned'),
            ('Withdraw applicant (internal)',         'Internal mark as withdrawn', 'planned'),
            ('Schedule interview',                    'Create interview record', 'planned'),
            ('Log interview feedback',                'Record notes/ratings after interview', 'planned'),
            ('Convert applicant to employee',         'Run conversion wizard to create Employee record', 'planned'),
            ('Detect duplicate applicants',           'System flags potential duplicates', 'planned'),
            ('Merge duplicate applicants',            'Merge two applicant records', 'planned'),
            ('Add applicant note',                    'Private/shared note on applicant', 'planned'),
            ('Create onboarding template',            'Reusable checklist', 'planned'),
            ('Assign onboarding checklist',           'To new hire after conversion', 'planned'),
            ('Complete onboarding tasks',             'Check off checklist items', 'planned'),
            ('Export applicant data (GDPR)',          'Subject access request', 'planned'),
            ('Process erasure request',               'Delete applicant data on GDPR request', 'planned'),
            ('Configure data retention periods',      'Admin sets category-specific retention', 'planned'),
            ('Filter applicants',                     'By opening, stage, date, tags', 'planned'),
        ],
    },

    # ═══ ROLES & PERMISSIONS ═══
    'roles-permissions': {
        'components': [
            ('Roles Directory',             'Main page listing all custom roles for the company', 'planned'),
            ('Create Role',                 'Popup for creating a new role — name, description, color, icon, permissions, default department', 'planned'),
            ('Edit Role',                   'Popup for editing role details and permissions', 'planned'),
            ('Role Detail Panel',           'Floating group showing role summary + assigned users + permission list', 'planned'),
            ('Permission Picker',           'Two-column layout: Group→Subgroup sidebar + checkboxes panel with search, filters, bulk actions', 'planned'),
            ('Copy From Role',              'Duplicate another role as starting point', 'planned'),
            ('Deactivate Role',             'Dialog for soft-deleting a role', 'planned'),
            ('Permission Requests Queue',   'Admin page listing pending/reviewed permission requests', 'planned'),
            ('Request Extra Permission',    'User-facing dialog for requesting extra permissions with justification', 'planned'),
            ('Review Permission Request',   'Admin dialog to approve/partial-approve/reject a request', 'planned'),
            ('Extra Permissions Manager',   'User profile section showing granted extras with expiry', 'planned'),
            ('Roles & Permissions Sidebar', 'Reusable component visible on every module page showing user\'s permissions and request capability', 'planned'),
        ],
        'features': [
            ('Create custom role',                   'Admin creates new role', 'planned'),
            ('Edit role',                            'Update name, description, permissions', 'planned'),
            ('Copy role from template',              'Duplicate existing role as starting point', 'planned'),
            ('Assign permissions to role',           'Via permission picker', 'planned'),
            ('Bulk-toggle permissions',              'Select all in a subgroup', 'planned'),
            ('Search permissions',                   'Find permission by name or code', 'planned'),
            ('Deactivate role (soft-delete)',        'Roles are never hard-deleted', 'planned'),
            ('Assign role to user',                  'One role per user (via User Management)', 'planned'),
            ('Request extra permission',             'User requests permission not in their role', 'planned'),
            ('View own permission requests',         'User sees pending/reviewed/expired requests', 'planned'),
            ('Cancel own permission request',        'Before admin reviews', 'planned'),
            ('Review permission request (admin)',    'Approve, partial-approve, or reject with note', 'planned'),
            ('Receive request-reviewed notification','Requester notified of decision', 'planned'),
            ('Auto-expire pending requests (30d)',   'System auto-expires old pending requests', 'planned'),
            ('See permissions required on page',     'Sidebar shows what permissions the current page needs', 'planned'),
            ('See missing permissions',              'Sidebar highlights what user is missing', 'planned'),
        ],
    },

    # ═══ NOTIFICATIONS ═══
    'notifications': {
        'components': [
            ('Notifications Bell Dropdown', 'Header bell icon + dropdown with recent notifications and counts', 'planned'),
            ('Notifications Full Page',     'Dedicated page showing all notifications with filters (Unread / Read / Archived)', 'planned'),
            ('Notification Preferences',    'User settings page for per-event opt-in/opt-out and channel choice', 'planned'),
            ('Watch / Follow Control',      'Subscribe/unsubscribe to a specific entity (report, task, etc.)', 'planned'),
            ('Email Notification Template', 'Master email layout with header, body, and unsubscribe link', 'planned'),
            ('Batched Notification Summary','"5 new comments on Report #123" when dedupe fires', 'planned'),
        ],
        'features': [
            ('Receive in-app notification',      'Bell dropdown + counter', 'planned'),
            ('Receive email notification',       'Via configured email template', 'planned'),
            ('Mark notification as read',        'Click or bulk action', 'planned'),
            ('Mark all as read',                 'Bulk action in full page', 'planned'),
            ('Archive notification',             'Move out of primary list', 'planned'),
            ('Watch an entity',                  'Subscribe to updates on a report/task/etc.', 'planned'),
            ('Unwatch entity',                   'Unsubscribe', 'planned'),
            ('Configure notification preferences','Per-event opt-in/out, channel choice (in-app / email / both)', 'planned'),
            ('Disable email for event type',     'Keep in-app only for certain events', 'planned'),
            ('Receive batched notification',     'Multiple events merged into one summary', 'planned'),
            ('Critical notification bypass',     'Certain events always deliver, overriding batching', 'planned'),
            ('Unsubscribe via email link',       'One-click unsubscribe from an event type', 'planned'),
        ],
    },

    # ═══ SYSTEM ACTIVITY LOG ═══
    'activity-log': {
        'components': [
            ('Activity Log Page',           'Filterable log of all system events with date/actor/subject filters', 'planned'),
            ('Per-Record Timeline',         'Activity feed scoped to one record (shown inside its detail view)', 'planned'),
            ('Activity Filters Sidebar',    'Filters by action, subject type, actor, date range', 'planned'),
            ('Export Activity Log',         'Export filtered results to CSV', 'planned'),
            ('Retention Settings',          'Admin panel for activity log retention rules', 'planned'),
        ],
        'features': [
            ('View company-wide activity log',  'Admin sees all events across company', 'planned'),
            ('View per-record timeline',        'See all events scoped to one record', 'planned'),
            ('Filter activity log',             'By action, subject, actor, date', 'planned'),
            ('Search activity log',             'Full-text search through descriptions', 'planned'),
            ('Export activity log to CSV',      'Download filtered subset', 'planned'),
            ('Auto-retain activity log',        'System honors configured retention period per action category', 'planned'),
        ],
    },

    # ═══ CASINO SETTINGS ═══
    'casino-settings': {
        'components': [
            ('Casino Settings Page',        'Admin settings hub with tabs for each settings group', 'planned'),
            ('Company Details',             'Legal name, address, contact info, tier', 'planned'),
            ('Property Manager',            'List + add/edit properties (multi-property v2)', 'planned'),
            ('Timezone & Locale',           'Per-property timezone, currency, locale config', 'planned'),
            ('Fiscal Week Config',          'Close-day-of-week and close-time per property', 'planned'),
            ('Branding & Letterhead',       'Logo upload (full + icon), letterhead for PDFs/emails', 'planned'),
            ('Numbering Config',            'Report/RFI/Task/Warning number formats and counter state', 'planned'),
            ('Data Model Principles Viewer','Read-only reference showing tenant-isolation + audit field conventions', 'planned'),
        ],
        'features': [
            ('Edit company details',            'Admin updates company info', 'planned'),
            ('Add property',                    'Multi-property v2 — create additional property', 'planned'),
            ('Edit property settings',          'Per-property timezone, currency, locale', 'planned'),
            ('Change fiscal week close day',    'Admin selects close day/time (critical permission)', 'planned'),
            ('Upload company logo',             'Logo full + icon versions', 'planned'),
            ('Configure letterhead',            'Appears on report PDFs and emails', 'planned'),
            ('Configure number format',         'Per-property prefix + padding for each entity type', 'planned'),
            ('View current counter state',      'See last-issued numbers', 'planned'),
            ('Edit critical settings',          'Timezone/currency/fiscal_week_start requires settings.edit_critical', 'planned'),
        ],
    },

    # ═══ USER MANAGEMENT ═══
    'user-management': {
        'components': [
            ('User Directory',              'Admin page listing all users with status, role, department filters', 'planned'),
            ('Create User',                 'Popup for creating a new user — email, name, role, department, property', 'planned'),
            ('Edit User',                   'Popup for editing user profile and role', 'planned'),
            ('User Detail Panel',           'Floating group with full user profile, roles, sessions, activity', 'planned'),
            ('User Profile Tab',            'Self-edit profile (name, avatar, contact)', 'planned'),
            ('Change Password',             'Popup for user to change own password', 'planned'),
            ('Reset Password (admin)',      'Admin-triggered password reset', 'planned'),
            ('Deactivate User',             'Admin dialog for deactivating a user', 'planned'),
            ('Anonymize User',              'Admin-only GDPR anonymization with typed confirmation', 'planned'),
            ('Session Manager',             'List active sessions + sign out other devices', 'planned'),
            ('Presence Indicator',          'Online/away/busy/offline status shown on avatars', 'planned'),
            ('2FA Setup',                   'Enroll + manage 2FA', 'planned'),
            ('User Preferences Panel',      'Notification settings, UI theme, language', 'planned'),
            ('Role Assignment',             'Assign/change role for a user (admin)', 'planned'),
        ],
        'features': [
            ('Log in',                          'Email + password authentication', 'planned'),
            ('Log out',                         'End session', 'planned'),
            ('Enroll 2FA',                      'Setup TOTP', 'planned'),
            ('Verify 2FA on login',             'When 2FA enrolled', 'planned'),
            ('Request password reset',          'Email-based reset flow', 'planned'),
            ('Change own password',             'From profile while logged in', 'planned'),
            ('Update own profile',              'Name, avatar, contact', 'planned'),
            ('Update preferences',              'Notifications, theme, language', 'planned'),
            ('Set presence status',             'Online / Away / Busy / Offline', 'planned'),
            ('View active sessions',            'See own signed-in devices', 'planned'),
            ('Sign out other devices',          'Revoke other sessions', 'planned'),
            ('Create user (admin)',             'Admin creates new user record', 'planned'),
            ('Assign role to user',             'Admin changes role', 'planned'),
            ('Assign departments / property',   'Scope user to dept / property', 'planned'),
            ('Deactivate user',                 'Reversible deactivation', 'planned'),
            ('Reactivate user',                 'Restore deactivated user', 'planned'),
            ('Anonymize user (GDPR)',           'Two-step: deactivate, then anonymize', 'planned'),
            ('Reset user password (admin)',     'Trigger reset on behalf of user', 'planned'),
            ('Filter user directory',           'By role, department, status, property', 'planned'),
        ],
    },
}


def get_components_features(module_id):
    """Returns (components, features) tuples for a module, or empty if not defined."""
    data = COMPONENTS_FEATURES.get(module_id, {})
    return data.get('components', []), data.get('features', [])
